### ISSUE TITLE
oracle.javacard:api_classic:jar:3.0.5 missing

### ISSUE THREAD

**Issue by biafra23** [licel/jcardsim#104]
When I try to build from master I get the error, that the artifact `oracle.javacard:api_classic:jar:3.0.5` cannot be found. Where can I find this?

>[ERROR] Failed to execute goal on project jcardsim: Could not resolve dependencies for project com.licel:jcardsim:jar:3.0.5-SNAPSHOT: Could not find artifact oracle.javacard:api_classic:jar:3.0.5 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by licel** [comment]
Please follow the building instructions: https://jcardsim.org/docs/getting-source-compiling.
