### ISSUE TITLE
Maven repository with 3.x.x series

### ISSUE THREAD

**Issue by rubdos** [licel/jcardsim#107]
It would be nice if the 3.x.x series were available at Maven Central (or another repo, for that matter). Makes cooperating on projects much easier.

**Comment by licel** [comment]
Thank you for raising the issue. As soon as we get everything needed in 3.0.x we will add jCardSim on Maven Central. It is not allowed to place SNAPSHOT versions there.

**Comment by licel** [comment]
https://github.com/licel/jcardsim/packages/1650016
