### ISSUE TITLE
Signature.ALG_ECDSA_SHA_256 is not available

### ISSUE THREAD

**Issue by biafra23** [licel/jcardsim#108]
It seems `Signature.getInstance()` throws a `CryptoException` when asked for a Signature of algorithm `Signature.ALG_ECDSA_SHA_256`

**Comment by biafra23** [comment]
I fixed this in my fork. I can provide a PR to fix this. Should I?

**Comment by licel** [comment]
That will be highly appreciated!

**Comment by biafra23** [comment]
PR: https://github.com/licel/jcardsim/pull/109

**Comment by licel** [comment]
Thanks for the awesome job!
