### ISSUE TITLE
AES-GCM (ALG_AES_GCM) is not supported.

### ISSUE THREAD

**Issue by mvondracek** [licel/jcardsim#153]
Hello,

support for AES-GCM ([`ALG_AES_GCM`](https://docs.oracle.com/javacard/3.0.5/api/javacardx/crypto/AEADCipher.html)) was [introduced in *Java Card Platform, Classic Edition 3.0.5*](https://docs.oracle.com/javacard/3.0.5/devnotes/index.html#GUID-99CB269D-7F81-48D8-9C7C-C0ADF742FC45) in `javacardx.crypto.AEADCipher` class.

According to current README.md, the simulator supports 3.0.5. However, when I try to use this mode, `CryptoException.NO_SUCH_ALGORITHM` is thrown. It has `reason` code set to `CryptoException.NO_SUCH_ALGORITHM`.

~~~java
AEADCipher c = (AEADCipher) AEADCipher.getInstance(AEADCipher.ALG_AES_GCM, false);
~~~

Based on [observation of simulator's `CipherProxy` class](https://github.com/licel/jcardsim/blob/6b438bcbad2d7d3302ac89052f4dd63de64429fe/src/main/java/com/licel/jcardsim/crypto/CipherProxy.java#L47-L57), I assume that the simulator currently does not fully support `ALG_AES_GCM` from 3.0.5. Is that right?

Is there a list of currently unsupported features concerning 3.0.5 (3.0.5u3)? Thanks.

**Comment by licel** [comment]
#187
