### ISSUE TITLE
Support of JCSystem.makeGlobalArray() call

### ISSUE THREAD

**Issue by gahcep** [licel/jcardsim#178]
Hi, all.

I'm using `jcardsim-3.0.4-SNAPSHOT.jar` version for running tests via **Maven**.

My code has two applets that work on a real hardware (Infineon), but don't work in the simulator.

My investigation ended up pretty soon - I found out that the problem was in the `JCSystem.makeGlobalArray(...,....)` API call.
Return value is always `null`.

Can someone shed some light on whether **jcardsim** supports working with GlobalArray?

P.S. Checking the [SimulatorSystem](https://jcardsim.org/jcardsim/com/licel/jcardsim/base/SimulatorSystem.html) page shows no mention of the `makeGlobalArray` API call.

Thanks!

**Comment by licel** [comment]
#180
