### ISSUE TITLE
Does jcardsim supports GlobalPlatform?

### ISSUE THREAD

**Issue by licel** [licel/jcardsim#7]
_From [meetbt...@gmail.com](https://code.google.com/u/116717782476736232490/) on September 28, 2012 10:12:20_

Can we simulate a security domain in jcardsim?

_Original issue: http://code.google.com/p/jcardsim/issues/detail?id=7_

**Comment by lhjncut** [comment]
Hi,

Does jCardSim supports GlobalPlatform now?

Thanks!

**Comment by licel** [comment]
Hi, this functionality is now available under our commercial support subscription, please email us for details at primary@licelus.com
