### ISSUE TITLE
Can not compile jCardSim

### ISSUE THREAD

**Issue by lumag** [licel/jcardsim#80]
Frech checkout of jCardSim fails with the following error:

```
$ mvn test
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Java Card Runime Environment Simulator 3.0.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for oracle.javacard:api_classic:jar:3.0.4 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.327 s
[INFO] Finished at: 2015-12-29T09:06:52+03:00
[INFO] Final Memory: 7M/148M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jcardsim: Could not resolve dependencies for project com.licel:jcardsim:jar:3.0.4-SNAPSHOT: Failure to find oracle.javacard:api_classic:jar:3.0.4 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by licel** [comment]
Hi Dmitry, 
Thank you for raising the issue, the getting source and compiling article has been modified and now contains the relevant steps that describe the building process - https://jcardsim.org/docs/getting-source-compiling

**Comment by lumag** [comment]
Hi @licel,

This doesn't help too much. The page talks about `settings.xml`, but there is no `settings.xml` in the downloaded source tree.

**Comment by lumag** [comment]
The error comes from Maven not being able to find the pom for Java Card. Indeed, there is no pom for oracle.javacard: https://repo1.maven.org/maven2/oracle/

**Comment by licel** [comment]
Sorry about that, there is a typo in the article. 

The settings.xml file is located in ${user.home}/.m2 (https://maven.apache.org/settings.html) and contains all the local Maven settings, 'mvn initialize' task installs required artifacts into your local maven-repository.

**Comment by lumag** [comment]
@licel ok, if I set the `jcdkLocation` in the `pom.xml`, building of jcardsim works. However if I move the `jcdkLocation` declaration to `settings.xml`, build fails with the same error.

**Comment by lumag** [comment]
@licel ok, finally got it to work, after adding an activation. However I'd ask you to expand that section. Not everybody is a Maven expert. Maybe a minimal settings.xml example in documentation would help in such cases.
Thanks for your help anyway!

**Comment by licel** [comment]
@lumag Absolutely, thank you for your feedback. We will expand the section and add an example. Happy Holidays!

**Comment by ph4r05** [comment]
@licel I was quite confused about the build too - I was not able to build JCardSim from [getting-source-compiling].

So I am attaching here how to configure `~/m2/settings.xml` also for others to get that working:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<settings>
  <profiles>
    <profile>
        <id>jc305</id>
        <activation>
          <activeByDefault>true</activeByDefault>
        </activation>
        <properties>
          <jcdkLocation>/Users/dusanklinec/workspace/jcard/libs-sdks/jc305u1_kit</jcdkLocation>
        </properties>
    </profile>
  </profiles>
</settings>
```

If you could add this example also to the [getting-source-compiling] it would be gold! Thanks!

[getting-source-compiling]: https://jcardsim.org/docs/getting-source-compiling

**Comment by gahcep** [comment]
Hi, @ph4r05 
I'm afraid, the xml file you attached has nothing with how required artifact is being handled and searched.
In my case, only `3.0.5.4` version works, whereas I wasn't be able to build `3.0,4`. Having properly configured `settings.xml` and `JC_CLASSIC_PATH` didn't make any differences.
I didn't figure out how to build `3.0.4` so just keep `3.0.5.4`
