### ISSUE TITLE
Result of 2+ RSA calls returns incorrect length of the result / emits crypto exception

### ISSUE THREAD

**Issue by dancvrcek** [licel/jcardsim#88]
You should be able to replicate but let us know if now. It is possible that the error only shows in particular circumstances - e.g., interleaving use of several instances of the simulator.

The operation in question is RSA decrypt (we tried with 1k as well as 2k keys and the error occurs in both), when called twice in a row, the second call will return incorrect length of the result.

**Comment by dancvrcek** [comment]
sorry - it's version 2.2.2 downloaded as a jar file

**Comment by frankmorgner** [comment]
Erstlesegeschichten l

**Comment by dancvrcek** [comment]
I believe a colleague of mine found the problem. A pull request will follow shortly - something about forgotten index initialization after doFinal().
